name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
    - name: make
      run: make USE_PGXS=1
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
